steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - '-c'
    - |
      echo $_PR_NUMBER > prnumber.txt
  id: "Save PR Number"
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
      URL="https://api.github.com/repos/bipinupd/test101/pulls/`cat prnumber.txt`/files"
      FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
      echo $FILES
  id: "List Files"
