steps:
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'git'
      - 'diff'
      - '--name-only'
      - '${BRANCH_NAME}'
      - 'master'
      - '>>'
      - 'difffiles.txt'
    id: "Get the Diff Files"
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
          cat files.txt
    id: "Read FILES"
