steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - '-c'
    - |
      URL="https://api.github.com/repos/bipinupd/test101/pulls/${_PR_NUMBER}/files" && \ 
      FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename') && \ 
      echo $FILES
  id: "Test"
